#!/usr/bin/env bash
set -Eeuo pipefail

shellcheck_bin="$(scripts/resolve-tool shellcheck)"

"${shellcheck_bin}" -x \
  install \
  uninstall \
  scripts/fmt \
  scripts/install-dev-deps \
  scripts/lint \
  scripts/lint-shell \
  scripts/resolve-tool
