name: CI

on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    uses: ./.github/workflows/on-workflow-call-shell-check.yml

  format:
    uses: ./.github/workflows/on-workflow-call-format.yml

  lint:
    needs: [shellcheck, format]
    uses: ./.github/workflows/on-workflow-call-lint.yml

  build:
    needs: [lint]
    uses: ./.github/workflows/on-workflow-call-build.yml

  test:
    needs:
      - build
    uses: ./.github/workflows/on-workflow-call-test.yml

  sanitizers:
    needs:
      - build
    uses: ./.github/workflows/on-workflow-call-sanitizers.yml

  install-uninstall:
    needs: [build, sanitizers]
    uses: ./.github/workflows/on-workflow-call-distros.yml
